from pydantic import BaseModel, Field

class TextRequest(BaseModel):
    text: str = Field(
        ...,
        title="Input Text",
        description="Text for processing",
        min_length=3,
    )

class TextResponse(BaseModel):
    result: str = Field(
        ...,
        title="Processed text",
        description="The output generated by model",
        min_length=3,
    )